export const GET_BLOG_POST = 'GET_BLOG_POST'
export const GET_HERO_SECTION = 'GET_HERO_SECTION';

export const GET_PAGE_CONFIG = 'GET_PAGE_CONFIG';

export const GET_GITHUB_USER = 'GET_GITHUB_USER';
export const GET_GITHUB_USER_REPOS = 'GET_GITHUB_USER_REPOS';
export const SET_LOADING = 'SET_LOADING';
